#!/bin/bash

#This test-patch script should serve as a 
#template for future patch scripts.
#20210805 KM4ACK

#Give this patch a unique name. A good idea is
#to give it the application name that is being 
#patched followed by the date. ie FLDIDI20210805

PATCHNAME=flmsg-20210806

PATCHFILE=$HOME/.config/patch
touch $PATCHFILE
###############################
#Patch script commands go here#
###############################
clear;echo;echo
echo "################################
This patch will take ~20 minutes
to complete. DO NOT close this
window! You will be notified once
the patch has completed.
################################"
sleep 3
sudo apt -y update

##################################
#	DEPENDS
##################################
#install needed depends
sudo apt-get install -y libfltk1.3-dev libjpeg9-dev libxft-dev libxinerama-dev libxcursor-dev libsndfile1-dev libsamplerate0-dev portaudio19-dev libpulse-dev libusb-1.0-0-dev texinfo libudev-dev

#download and compile FLMSG 4.0.19
cd $HOME/Downloads
wget http://www.w1hkj.com/files/flmsg/flmsg-4.0.19.tar.gz
tar -zxvf flmsg-4.0.19.tar.gz
rm flmsg-4.0.19.tar.gz
cd flmsg-4.0.19
./configure --prefix=/usr/local --enable-static --without-flxmlrpc
make
sudo make install
sudo ldconfig


#############################################
#write patch name to a file so we can       #
#look and see if it has been applied before.#
#This is checked by the patch-menu script   #
#before running the patch                   #
#############################################
echo "$PATCHNAME" >> $PATCHFILE
