#!/bin/bash

#This test-patch script should serve as a 
#template for future patch scripts.
#20210805 KM4ACK

#Give this patch a unique name. A good idea is
#to give it the application name that is being 
#patched followed by the date. ie FLDIDI20210805

PATCHNAME=gridtracker20211222

PATCHFILE=$HOME/.config/patch
touch $PATCHFILE
###############################
#Patch script commands go here#
###############################
	cd ${HOME} || return
	sudo apt-get install -y libgconf-2-4
	GRIDDLL=$(curl -s https://download.gridtracker.org/latest_release.html | grep arm32 | sed 's/.*href="//;s/">.*//')
	wget --tries 2 --connect-timeout=60 $GRIDDLL
	GRIDTAR=$(echo $GRIDDLL | sed 's/.*\///g')
	tar -xzvf $GRIDTAR
	rm GridTracker*.gz
	OLDFOLDER=$(ls | grep GridTracker*-linux-arm32)
	mv "$OLDFOLDER" $HOME/GridTracker
	cat >gridtracker.desktop <<EOF
[Desktop Entry]
Name=GridTracker
Comment=GridTracker
GenericName=GridTracker, a WSJT-X Companion
Exec=${HOME}/GridTracker/GridTracker --disable-accelerated-2d-canvas --num-raster-threads=2
Icon=${HOME}/GridTracker/gridtracker.png
Path=${HOME}/GridTracker
Type=Application
Encoding=UTF-8
Terminal=false
Categories=HamRadio;
EOF

	sudo mv gridtracker.desktop /usr/share/applications/


#############################################
#write patch name to a file so we can       #
#look and see if it has been applied before.#
#This is checked by the patch-menu script   #
#before running the patch                   #
#############################################
echo "$PATCHNAME" >> $PATCHFILE
