#!/bin/bash

#This test-patch script should serve as a 
#template for future patch scripts.
#20210805 KM4ACK

#Give this patch a unique name. A good idea is
#to give it the application name that is being 
#patched followed by the date. ie FLDIDI20210805

PATCHNAME=test-patch20210805

PATCHFILE=$HOME/.config/patch
touch $PATCHFILE
###############################
#Patch script commands go here#
###############################
clear;echo;echo
echo "This is a test patch"


#############################################
#write patch name to a file so we can       #
#look and see if it has been applied before.#
#This is checked by the patch-menu script   #
#before running the patch                   #
#############################################
echo "$PATCHNAME" >> $PATCHFILE
