#!/bin/bash

#script get maidenhead from GPS for display in conky
#called by cronjob
#04FEB2021 KM4ACK

GRID=$($HOME/bin/conky/get-grid)
GRIDCH=$(echo $GRID | grep -i JJ00)
FILE=/run/user/$UID/gridinfo.txt

if [ -z "$GRIDCH" ]
then
  # + = Grid from GPS (GPS online)
  # - = Grid from Cache (GPS offline)
  if [ "$GRID" != "NO GPS" ]; then
    echo "$GRID +" > $FILE
  else
    cache=$(cat $FILE | sed 's/ //g;s/+//g;s/-//g')
    echo "$cache -" > $FILE
  fi
else
echo "NO GPS" > $FILE
fi
